# Generated by Django 6.0.4 on 2026-05-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=50)),
                ('Student_branch', models.CharField(max_length=20)),
            ],
        ),
    ]
