# Generated by Django 6.0.3 on 2026-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_branch',
            field=models.CharField(max_length=50),
        ),
    ]
